package protocol

import (
	"errors"
	"fmt"
	"strings"
)

// ErrOverBudget is returned, wrapped, when a rendered target exceeds its byte
// budget. RenderAll never truncates to fit a budget: a silently truncated
// AGENTS.md would pass a byte-comparison drift check while being wrong.
var ErrOverBudget = errors.New("rendered output exceeds the target's byte budget")

// Target renders one Doc into one agent front-end.
type Target struct {
	Name     string
	OutPath  string
	MaxBytes int
	Required []string
	Render   func(d *Doc) (string, error)
	Validate func(out string) error
}

// Generated marks every output so a reader knows where to edit.
const Generated = "<!-- GENERATED by `rtdd-gen render` from protocol/PROTOCOL.md. Do not edit. -->"

// AGENTS.md and CLAUDE.md are host-owned files, so the block that goes into them
// is delimited and `rtdd init` only ever touches what is between these markers.
const (
	BeginMarker = "<!-- BEGIN rtdd (generated from protocol/PROTOCOL.md; do not edit here) -->"
	EndMarker   = "<!-- END rtdd -->"
)

func requireSections(d *Doc, t Target) error {
	present := map[string]bool{}
	for _, s := range d.For(t.Name) {
		present[s.ID] = true
	}
	var missing []string
	for _, id := range t.Required {
		if !present[id] {
			missing = append(missing, id)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("target %q is missing required sections %v", t.Name, missing)
	}
	return nil
}

func renderSkill(d *Doc) (string, error) {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("name: rtdd\n")
	b.WriteString("description: " + SkillDescription + "\n")
	b.WriteString("---\n\n")
	b.WriteString(Generated + "\n\n")
	b.WriteString("# rtdd\n\n")
	for _, s := range d.For("skill") {
		b.WriteString("## " + s.Title + "\n\n")
		b.WriteString(s.BodyFor("skill") + "\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

func renderAgents(d *Doc) (string, error) {
	var b strings.Builder
	b.WriteString(BeginMarker + "\n")
	b.WriteString("## rtdd\n\n")
	for _, s := range d.For("agents") {
		b.WriteString(s.BodyFor("agents") + "\n\n")
	}
	b.WriteString(EndMarker + "\n")
	return b.String(), nil
}

func renderMDC(d *Doc) (string, error) {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("description: " + MdcDescription + "\n")
	b.WriteString("globs: " + MdcGlobs + "\n")
	b.WriteString("alwaysApply: false\n")
	b.WriteString("---\n\n")
	b.WriteString(Generated + "\n\n")
	b.WriteString("# rtdd\n\n")
	for _, s := range d.For("mdc") {
		b.WriteString("## " + s.Title + "\n\n")
		b.WriteString(s.BodyFor("mdc") + "\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// noValidate is the placeholder Target.Validate until issue #194 (per-target
// validity assertions) wires in the real validateSkill/validateAgents/validateMDC.
func noValidate(string) error { return nil }

// RenderAll renders every target, enforcing required sections, byte budgets, and
// per-target validity. A budget overflow is an error, never a truncation.
func RenderAll(d *Doc) (map[string]string, error) {
	out := make(map[string]string, len(Targets))
	for _, t := range Targets {
		if err := requireSections(d, t); err != nil {
			return nil, err
		}
		body, err := t.Render(d)
		if err != nil {
			return nil, fmt.Errorf("render %s: %w", t.Name, err)
		}
		if len(body) > t.MaxBytes {
			return nil, fmt.Errorf(
				"%w: %s is %d bytes, budget %d — shorten the target's variants, do not raise the budget",
				ErrOverBudget, t.OutPath, len(body), t.MaxBytes)
		}
		if err := t.Validate(body); err != nil {
			return nil, fmt.Errorf("validate %s: %w", t.OutPath, err)
		}
		out[t.OutPath] = body
	}
	return out, nil
}
